/**
 * 地球陆地点阵：在球面上取 16000 个斐波那契格点（等面积、无极点堆积），
 * 用 global-land-mask（约 1 km 分辨率的海陆掩膜）逐点判定后打包为位图；
 * 0.6° 之内有陆地的格点也计入，使细小岛屿可见。共 5180 个陆地点。
 */
const N = 16000
const DATA = 'AAAAAAAQAIQEJCQxoQ0pCElCaEITUJCUhIakZyEwuQnATO4CZFMTgZicQOBmdxMzOZnEzM4kZrM7pZ3/bu9fb9s739X2/re3/7+77b3vb/9/W9v//97+/v+3//etrd//bn9/W9uf/9ze/7e1P7+p7c/vam9/+9qe3tT27/e1Pbvt7U/vand3+9qe3Nb05/c1M7nZyU/uan5zM5aZ3MT053clNzmJy87OYn5zu5ebnM7t52cjPzndy87OQn7zs5efnOzs52cnvznZy+7Oenb7s5efnKzt52cvO3nZy8/OXnZzs5ednOzl52cvOznZy87OVnZzs5ecnKzt52cvOTnZy85OVnbzs5WcnKzt52crOTnZys7OVnJzsxWdnKzl52crOTnZys7OVmLzs5ecnMzlZ2crOXnZi85eVmKzs5ecvMTF5ycrMVnJic5ednKzkxWcrOTk5y8jOVmJyM5WcnIzk5WcrOTl5yshOVnJyM5WYjLzl5GcrMRkZyspORnJyM5WcnJzl5CcrMRlZys5OXnJyk5WYnKzkZCcvMRlZycxOXmJykxeYjKzlZCcvMTlJi8xGVmIyExeYjKzF5CcrMRlJi8xGVmLykxWcjKTFZCcrOVlJishGUnLyk5WcjKTlZSMpOXlJyspGUnKyk5WcrKTlZSMpOXlJys5GUnKCk5WcrKTlJSspOVlJyspWUnKCkZSUpKTlJSspOUlLys5aUnKClZSUpKTlJSkpOUlIys5SUnKClZScpKRFJSkpOUlKyk5SUnKClJWUpKTFJSkoOUlKyo5SUjKSlJQUpKVFZSkoGUlKSg5SUPKylJQUpKVlZSkoGVlKSgpWUrKylJRMpKVlQSsoGUlKSoJWUqCSlJVMpKVlQSsoWElKSgJSUKCAlZVMJCVlASsoeElKyoISVqCglZUcJCVlQSkqWEBKyoISUqCAlZQ8ICVlAQkoWEBKygIQUrKAhZQkICVlAQooWEBKyhoQUpCAhZQkICVlAQopSEBCyhoQUpCAhRQ0ICVlAQgpSEBCihoQEpKghRQkoCEFDQgpSEBCihoQEoKihBQkICEhDQgLQFBCihoQEpCghBWkKCElTQgJSVBCipIUEJCghAWkKCFFTQoJSVBCgpIUEJCihQWkqKEBTQoJSVBCgpIUEICihQUkqCEBTSoJSFFCgpIUUICihQWkqKEBSSoqQFBCApIUUICghQUkqCABSSoqQFBCApIUEACghRUAqCABSSoqAFBAioBUEACglRUAqCABQSoKAFBAioBUEAKglRUAKCBFQCoKAFFCioBUUCKgFRUAKCBFQCooAVFCioAUUCKhFRUAKCFFQCoqEVACioBUECKjFRUAKAFFRCoKEVECgogUEKKiFRUIKIFFRCoqEVECiogUBKKiFRUYqIlBRCoqEVECiogURKKiFQUYKAlFRAoiEFECiowUBKCiFQEYKAlFRAoCEFACiowUBOCiFQEYKIlBRioCMFACgoxUBKCiFQEYKIlBRioCUFEDgIxUBKKiFwEYqAFFRioiUVEDiIxUBKKiBQEYqAFFQgoCUVADgIwUAKCgBQE4KAFBQgoCUFADgIwUAKCgBQEoKAFAQgogUFECiIQUAKChBREoKAHAQgogUFECiJQUAKAhBRQoKIFAQgokUFECiBQUAKIhBxYoKIFESgoAUVECihQUAKIhBxAoKIFFSgoAUTADihQUQKKlBRAoqIFFCgoAURACiBRUQKKlBRAomIFFCgogUVICiBREQKKFBRAoiIFFCiIgUVICiBREQKKFFRAoiIFECiIgUUIKiBREQKKFERAoqIVECiIgcUKKiBREQqIFERAooIVECiIhUUKKiBRUQqIFERAooUVECiAhUQKIiBRQQqIFEBAooUVECiAhUQKICBRQQqIFEBCogURECiAhUQKICBRA4iIFEBCogUQECiAhUQKICBRA4iIFEBCogUQECiAxEQKICFRAoiIFEBCogUQECiAxEQKICFRAogIFEBiIgUQECiAxAQKICERAogIFEBiAgUQECiARAQKICERAogIFEBiAgUQEIiBRAQKADEBAoAIBAAiAgUAEIiBQAQCABEBAoAIBEAgAgEAGICAQAQCABAhAIAIAEAgAgEACAAAQAQAABAhAIAMAAAgQgEACACAQAQAABAhAIAEAAAgQgAACBAAQAIAABAgAAAEAAAgAAAACBAAAAIAABABAAAECAAAAwAACAAAAAIEAAABAAAEAAAAAQAACAAAAAIEAAAAAAAEAAAAAQIAAAAAAAIAAAAAgQAEAAAAAQAAAABAgAIAAAAAgQAAAAAAAQAAAABAAAIAAAAAgAAAAAAAAYAAAABAAAAAAAAAgAAAACAAAAAAAABAAAAAAAAAgAAAACAAAAAACABAAAAAAAAAgAAAACAAAAAAAAhAAAAAAAAAgAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAQAAAAAAAAABAAAAgAAAEgAQEBCABKREISEpGQlICkpCUiKSkJScpKTlJykpcUtLWl5S0veWlry85aXvPy15e8vPXn7z8/efvPz95++/P/n779//fn7399+f/f3/7++/f/////////8='

let cache: Array<{ lat: number; lon: number }> | null = null
export function landPoints() {
  if (cache) return cache
  const binary = atob(DATA)
  const golden = Math.PI * (3 - Math.sqrt(5))
  const points: Array<{ lat: number; lon: number }> = []
  for (let i = 0; i < N; i++) {
    if (!((binary.charCodeAt(i >> 3) >> (7 - (i & 7))) & 1)) continue
    const y = 1 - (2 * (i + 0.5)) / N
    const lat = (Math.asin(y) * 180) / Math.PI
    const lon = ((((i * golden) % (2 * Math.PI)) * 180) / Math.PI) - 180
    points.push({ lat, lon })
  }
  cache = points
  return points
}
